### ISSUE TITLE
predict problem

### ISSUE THREAD

**Issue by suke27** [dmaniry/deepIQA#9]
Hi, I try to run you programs, it seems for same input images, every time output score is not same. is there problem for my predict process

**Comment by dumpling426** [comment]
Me too...I have the same problem:(

**Comment by liujiang137** [comment]
> Hi, I try to run you programs, it seems for same input images, every time output score is not same. is there problem for my predict process

Have you successfully run evaluate.py? I want to know how to edit configuration.whether MODEL  is in models?,but  I can't run it.thanks for your reply in advance.

**Comment by WolframRhodium** [comment]
The problem arises since Chainer runs in training mode by default, when [dropout](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.dropout.html) drops data randomly. The non-deterministic convolutions using cuDNN may also bring marginal uncertainty. To fix them, one should set
```python
chainer.global_config.train = False
chainer.global_config.cudnn_deterministic = True
```
in `evaluate.py` before evaluation. 

[Reference](https://docs.chainer.org/en/stable/reference/configuration.html)

**Comment by wunderwuzzi1975** [comment]
@WolframRhodium Thank you for pointing out the changes needed for fixing the non-deterministic behaviour. I have modified evaluate.py accordingly and created a PR.
